# -*- mode: makefile -*-

NAME= kif-lib
PACKAGE= $(shell ${PYTHON} -c 'import kif_lib; print(kif_lib.__title__)')
VERSION= $(shell ${PYTHON} -c 'import kif_lib; print(kif_lib.__version__)')
DESCRIPTION= $(shell ${PYTHON} -c 'import kif_lib; print(kif_lib.__description__)')
AUTHOR= IBM
EMAIL= Guilherme.Lima@ibm.com
URL= https://github.com/IBM/kif
URL_SSH= git@github.com:IBM/kif.git

COPYRIGHT= IBM Corp.
COPYRIGHT_START_YEAR= 2023
LICENSE= Apache-2.0

SETUP_PY_CLASSIFIERS= [\
    'License :: OSI Approved :: Apache Software License',\
    'Programming Language :: Python',\
    'Programming Language :: Python :: 3',\
    'Programming Language :: Python :: 3.9',\
    'Programming Language :: Python :: 3.10',\
    'Programming Language :: Python :: 3.11',\
    'Programming Language :: Python :: 3.12',\
    'Programming Language :: Python :: 3.13',\
    'Programming Language :: Python :: 3.14',\
  ]

SETUP_PY_PACKAGE_DATA= {\
    '${PACKAGE}': ['py.typed'],\
  }

SETUP_PY_ENTRY_POINTS= {\
    'console_scripts': ['kif = kif_lib.cli:cli'],\
  }

SETUP_PY_INSTALL_REQUIRES= [\
    'httpx',\
    'lark',\
    'more_itertools',\
    'networkx',\
    'rdflib',\
    'types-networkx',\
    'typing-extensions',\
  ]

SETUP_PY_EXTRAS_REQUIRE= {\
    'cli': ${SETUP_PY_EXTRAS_REQUIRE_CLI},\
    'extra': ${SETUP_PY_EXTRAS_REQUIRE_EXTRA},\
  }

SETUP_PY_EXTRAS_REQUIRE_CLI= [\
    'click',\
    'rich',\
  ]

SETUP_PY_EXTRAS_REQUIRE_EXTRA= [\
    'ddgs',\
    'graphviz',\
    'jpype1',\
    'pandas',\
    'pandas-stubs',\
    'psutil',\
    'types-click',\
    'types-psutil',\
  ]

CHECK_PYLINT= no
CHECKFAST= ${TOX_SETENV}
COVERAGERC_EXCLUDE_LINES+= <line>raise \w+\._should_not_get_here</line>
COVERAGERC_EXCLUDE_LINES+= <line>raise ShouldNotGetHere</line>
DOCS_SETENV= KIF_RESOLVE_ENTITIES=1
ISORT_CFG_ADD_IMPORTS= from __future__ import annotations
MYPY_OPTIONS=
PYLINT_OPERANDS= ${PACKAGE}
PYLINTRC_DISABLE+= <line>abstract-method,</line>
PYLINTRC_DISABLE+= <line>arguments-differ,</line>
PYLINTRC_DISABLE+= <line>arguments-out-of-order,</line>
PYLINTRC_DISABLE+= <line>bad-mcs-classmethod-argument,</line>
PYLINTRC_DISABLE+= <line>consider-using-in,</line>
PYLINTRC_DISABLE+= <line>cyclic-import,</line>
PYLINTRC_DISABLE+= <line>duplicate-code,</line>
PYLINTRC_DISABLE+= <line>import-outside-toplevel,</line>
PYLINTRC_DISABLE+= <line>invalid-name,</line>
PYLINTRC_DISABLE+= <line>missing-function-docstring,</line>
PYLINTRC_DISABLE+= <line>missing-module-docstring,</line>
PYLINTRC_DISABLE+= <line>no-else-continue,</line>
PYLINTRC_DISABLE+= <line>no-else-raise,</line>
PYLINTRC_DISABLE+= <line>no-else-return,</line>
PYLINTRC_DISABLE+= <line>no-member,</line>
PYLINTRC_DISABLE+= <line>no-name-in-module,</line>
PYLINTRC_DISABLE+= <line>protected-access,</line>
PYLINTRC_DISABLE+= <line>redefined-builtin,</line>
PYLINTRC_DISABLE+= <line>superfluous-parens,</line>
PYLINTRC_DISABLE+= <line>too-few-public-methods,</line>
PYLINTRC_DISABLE+= <line>too-many-ancestors,</line>
PYLINTRC_DISABLE+= <line>too-many-arguments,</line>
PYLINTRC_DISABLE+= <line>too-many-boolean-expressions,</line>
PYLINTRC_DISABLE+= <line>too-many-branches,</line>
PYLINTRC_DISABLE+= <line>too-many-instance-attributes,</line>
PYLINTRC_DISABLE+= <line>too-many-lines,</line>
PYLINTRC_DISABLE+= <line>too-many-locals,</line>
PYLINTRC_DISABLE+= <line>too-many-nested-blocks,</line>
PYLINTRC_DISABLE+= <line>too-many-public-methods,</line>
PYLINTRC_DISABLE+= <line>too-many-return-statements,</line>
PYLINTRC_DISABLE+= <line>too-many-statements,</line>
PYLINTRC_DISABLE+= <line>unidiomatic-typecheck,</line>
PYLINTRC_DISABLE+= <line>unnecessary-lambda-assignment,</line>
PYLINTRC_DISABLE+= <line>unsupported-binary-operation,</line>
PYLINTRC_DISABLE+= <line>unused-argument,</line>
PYLINTRC_DISABLE+= <line>unused-import,</line>
PYRIGHTCONFIG_EXCLUDE= ["kif_lib/vocabulary/wd/property.py", "tests/model/test_object.py"]
PYTEST_OPTIONS+= --ignore tests/model/test_object.py --ignore tests/tests
TOX_INI_EXTRAS= all
TOX_INI_PASSENV+= <line>DBPEDIA</line>
TOX_INI_PASSENV+= <line>JAVA_HOME</line>
TOX_INI_PASSENV+= <line>JENA_HOME</line>
TOX_INI_PASSENV+= <line>PUBCHEM</line>
TOX_INI_PASSENV+= <line>WIKIDATA</line>
TOX_SETENV= DBPEDIA='' JENA_HOME='${JENA_HOME}' PUBCHEM='' WIKIDATA=''

# Set WIKIDATA and PUBCHEM in your local Makefile.
-include Makefile_local.conf
PYTEST_SETENV+= DBPEDIA='${DBPEDIA}'
PYTEST_SETENV+= JENA_HOME='${JENA_HOME}'
PYTEST_SETENV+= PUBCHEM='${PUBCHEM}'
PYTEST_SETENV+= PYTHONASYNCIODEBUG=1
PYTEST_SETENV+= WIKIDATA='${WIKIDATA}'

# -- README.md -------------------------------------------------------------

readme_md_sed=\
  -e 's|img/kif-b.svg\#only-light|docs/img/kif-b.svg\#gh-light-mode-only|g'\
  -e 's|img/kif-w.svg\#only-dark|docs/img/kif-w.svg\#gh-dark-mode-only|g'\
  ${NULL}

README.md: docs/index.md
	$P 'generating $@'
	@${SED} ${readme_md_sed} <$^ >$@

# generate README.md
.PHONY: gen-readme-md
gen-readme-md: README.md

GEN_ALL_TARGETS+= gen-readme-md

# == Vocabulary dumps ======================================================

KIF= kif

dump_sort_py=\
  fin, fout = open("$1"), open("$2", "a");\
  entries = list(map(str.strip, sorted(fin, key=str.casefold)));\
  entries += [a.strip() for a in "$3".split(";") if a.strip()];\
  vars = (e.split("=")[0].strip() for e in entries);\
  print(*entries, sep="\n", file=fout);\
  print(file=fout);\
  print("__all__ = (\n" + ",\n".join((f"\"{v}\"" for v in vars)) + "\n)", file=fout);\
  ${NULL}

define dump_tpl=
.PHONY: $1
$1: $2
	echo '# Copyright (C) $$(strip $4) IBM Corp.' >$$@
	echo '# SPDX-License-Identifier: Apache-2.0' >>$$@
	echo '#' >>$$@
	echo '# $$$$Id$$$$' >>$$@
	echo '#' >>$$@
	echo '# ** GENERATED FILE: DO NOT EDIT! **' >>$$@
	echo >>$$@
	echo 'from __future__ import annotations' >>$$@
	echo >>$$@
	echo '$$(strip $5)' >>$$@
	echo >>$$@
	echo '# pyright: ignore' >>$$@
	echo '# autopep8: off' >>$$@
	echo '# flake8: noqa' >>$$@
	echo >>$$@
	${PYTHON} -c '$(call dump_sort_py,$$^,$$@,$6)'
	${PYTHON} -m isort $$@
$2:
	mkdir -p $$(shell dirname $$@)
	$3 >$$@
endef

dump_x_item_import_py= from ...model import IRI, Item, Text

dump_x_property_import_py=\
  from ...model import (\
    ExternalIdDatatype,\
    IRI,\
    IRI_Datatype,\
    Item,\
    ItemDatatype,\
    LexemeDatatype,\
    Property,\
    PropertyDatatype,\
    QuantityDatatype,\
    StringDatatype,\
    Text,\
    TextDatatype,\
    TimeDatatype,\
  )\
  ${NULL}

# -- DBpedia ---------------------------------------------------------------

DUMP_DB_PROPERTY= kif_lib/vocabulary/db/property.py
DUMP_DB_PROPERTY_CACHE= .cache/${DUMP_DB_PROPERTY}
DUMP_DB_PROPERTY_KIF=\
  KIF_STORE_PAGE_SIZE=1000\
  ${KIF} -i filter -s dbpedia\
    --subject-is-property --language=en --select s\
    --vocabulary-dump=name --page-size=15000 --no-async\
  ${NULL}

# dump DBpedia properties
.PHONY: dump-db-property
dump-db-property: ${DUMP_DB_PROPERTY}

$(eval $(call dump_tpl,\
  ${DUMP_DB_PROPERTY},\
  ${DUMP_DB_PROPERTY_CACHE},\
  ${DUMP_DB_PROPERTY_KIF},\
  2025,\
  ${dump_x_property_import_py}))

# -- FactGrid --------------------------------------------------------------

DUMP_FG_PROPERTY= kif_lib/vocabulary/fg/property.py
DUMP_FG_PROPERTY_CACHE= .cache/${DUMP_FG_PROPERTY}
DUMP_FG_PROPERTY_KIF=\
  KIF_STORE_PAGE_SIZE=1000\
  ${KIF} -i filter -s factgrid --property=wd.a --value='fg.Q(21878)'\
    --subject-is-property --language=en --select s\
    --vocabulary-dump=label --page-size=15000 --no-async\
  ${NULL}

# dump FactGrid properties
.PHONY: dump-fg-property
dump-fg-property: ${DUMP_FG_PROPERTY}

$(eval $(call dump_tpl,\
  ${DUMP_FG_PROPERTY},\
  ${DUMP_FG_PROPERTY_CACHE},\
  ${DUMP_FG_PROPERTY_KIF},\
  2025,\
  ${dump_x_property_import_py}))

# -- Wikidata --------------------------------------------------------------

_DUMP_WD_X_KIF=\
  KIF_STORE_PAGE_SIZE=1000\
  ${KIF} -i filter --language=en --select=s --vocabulary-dump=label\
    --page-size=15000 --no-async\
  ${NULL}

DUMP_WD_PROPERTY= kif_lib/vocabulary/wd/property.py
DUMP_WD_PROPERTY_CACHE= .cache/${DUMP_WD_PROPERTY}
DUMP_WD_PROPERTY_KIF=\
  ${_DUMP_WD_X_KIF}\
    --property=wd.a --value=wd.Wikidata_property_ --subject-is-property\
  ${NULL}

dump_wd_property_aliases=\
  has_part = has_parts;\
  material_produced = product_or_material_produced;\
  median_lethal_dose = median_lethal_dose_LD50;\
  ${NULL}

# dump Wikidata properties
.PHONY: dump-wd-property
dump-wd-property: ${DUMP_WD_PROPERTY}

$(eval $(call dump_tpl,\
  ${DUMP_WD_PROPERTY},\
  ${DUMP_WD_PROPERTY_CACHE},\
  ${DUMP_WD_PROPERTY_KIF},\
  2024-2025,\
  ${dump_x_property_import_py},\
  ${dump_wd_property_aliases}))

DUMP_WD_ITEM_COUNTRY= kif_lib/vocabulary/wd/item_country.py
DUMP_WD_ITEM_COUNTRY_CACHE= .cache/${DUMP_WD_ITEM_COUNTRY}
DUMP_WD_ITEM_COUNTRY_KIF=\
  ${_DUMP_WD_X_KIF} --property=wd.instance_of --value=wd.country_\
    --subject-is-item\
  ${NULL}

# dump Wikidata country items
.PHONY: dump-wd-item-country
dump-wd-item-country: ${DUMP_WD_ITEM_COUNTRY}

$(eval $(call dump_tpl,\
  ${DUMP_WD_ITEM_COUNTRY},\
  ${DUMP_WD_ITEM_COUNTRY_CACHE},\
  ${DUMP_WD_ITEM_COUNTRY_KIF},\
  2025,\
  ${dump_x_item_import_py}))
