# Copyright (C) 2024 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

from .data_value import (
    DataValue,
    DataValueClass,
    DataValueTemplate,
    DataValueTemplateClass,
    DataValueVariable,
    DataValueVariableClass,
)
from .datatype import (
    Datatype,
    DatatypeClass,
    DatatypeVariable,
    DatatypeVariableClass,
    TDatatypeClass,
    VDatatype,
    VTDatatype,
    VVDatatype,
)
from .deep_data_value import (
    DeepDataValue,
    DeepDataValueClass,
    DeepDataValueTemplate,
    DeepDataValueTemplateClass,
    DeepDataValueVariable,
    DeepDataValueVariableClass,
)
from .entity import (
    Entity,
    EntityClass,
    EntityTemplate,
    EntityTemplateClass,
    EntityVariable,
    EntityVariableClass,
    TEntity,
    VEntity,
    VTEntity,
)
from .external_id import (
    ExternalId,
    ExternalIdClass,
    ExternalIdDatatype,
    ExternalIdDatatypeClass,
    ExternalIdTemplate,
    ExternalIdTemplateClass,
    ExternalIdVariable,
    ExternalIdVariableClass,
    TExternalId,
    VExternalId,
)
from .iri import (
    IRI,
    IRI_Datatype,
    IRI_Template,
    IRI_Variable,
    T_IRI,
    V_IRI,
    VT_IRI,
)
from .item import (
    Item,
    ItemDatatype,
    Items,
    ItemTemplate,
    ItemVariable,
    TItem,
    VItem,
    VTItem,
)
from .lexeme import (
    Lexeme,
    LexemeDatatype,
    Lexemes,
    LexemeTemplate,
    LexemeVariable,
    TLexeme,
    VLexeme,
)
from .property import (
    Properties,
    Property,
    PropertyDatatype,
    PropertyTemplate,
    PropertyVariable,
    TProperty,
    VProperty,
    VTProperty,
)
from .quantity import (
    Quantity,
    QuantityDatatype,
    QuantityTemplate,
    QuantityVariable,
    TQuantity,
    VQuantity,
)
from .shallow_data_value import (
    ShallowDataValue,
    ShallowDataValueClass,
    ShallowDataValueTemplate,
    ShallowDataValueTemplateClass,
    ShallowDataValueVariable,
    ShallowDataValueVariableClass,
)
from .string import (
    String,
    StringDatatype,
    StringTemplate,
    StringVariable,
    TString,
    VString,
)
from .text import Text, TextDatatype, TextTemplate, TextVariable, TText, VText
from .time import (
    Time,
    TimeDatatype,
    TimeTemplate,
    TimeVariable,
    TTime,
    TTimePrecision,
    VTime,
)
from .value import (
    TValue,
    Value,
    ValueClass,
    ValueTemplate,
    ValueTemplateClass,
    ValueVariable,
    ValueVariableClass,
    VTValue,
    VValue,
)

__all__ = (

    # datatype
    'Datatype',
    'DatatypeClass',
    'DatatypeVariable',
    'DatatypeVariableClass',
    'TDatatypeClass',
    'VDatatype',
    'VTDatatype',
    'VVDatatype',

    # value
    'TValue',
    'Value',
    'ValueClass',
    'ValueTemplate',
    'ValueTemplateClass',
    'ValueVariable',
    'ValueVariableClass',
    'VTValue',
    'VValue',

    # ----------

    'DataValue',
    'DataValueClass',
    'DataValueTemplate',
    'DataValueTemplateClass',
    'DataValueVariable',
    'DataValueVariableClass',
    'DeepDataValue',
    'DeepDataValueClass',
    'DeepDataValueTemplate',
    'DeepDataValueTemplateClass',
    'DeepDataValueVariable',
    'DeepDataValueVariableClass',
    'Entity',
    'EntityClass',
    'EntityTemplate',
    'EntityTemplateClass',
    'EntityVariable',
    'EntityVariableClass',
    'ExternalId',
    'ExternalIdClass',
    'ExternalIdDatatype',
    'ExternalIdDatatypeClass',
    'ExternalIdTemplate',
    'ExternalIdTemplateClass',
    'ExternalIdVariable',
    'ExternalIdVariableClass',
    'IRI',
    'IRI_Datatype',
    'IRI_Template',
    'IRI_Variable',
    'Item',
    'ItemDatatype',
    'Items',
    'ItemTemplate',
    'ItemVariable',
    'Lexeme',
    'LexemeDatatype',
    'Lexemes',
    'LexemeTemplate',
    'LexemeVariable',
    'Properties',
    'Property',
    'PropertyDatatype',
    'PropertyTemplate',
    'PropertyVariable',
    'Quantity',
    'QuantityDatatype',
    'QuantityTemplate',
    'QuantityVariable',
    'ShallowDataValue',
    'ShallowDataValueClass',
    'ShallowDataValueTemplate',
    'ShallowDataValueTemplateClass',
    'ShallowDataValueVariable',
    'ShallowDataValueVariableClass',
    'String',
    'StringDatatype',
    'StringTemplate',
    'StringVariable',
    'T_IRI',
    'TDatatypeClass',
    'TEntity',
    'Text',
    'TextDatatype',
    'TExternalId',
    'TextTemplate',
    'TextVariable',
    'Time',
    'TimeDatatype',
    'TimeTemplate',
    'TimeVariable',
    'TItem',
    'TLexeme',
    'TProperty',
    'TQuantity',
    'TString',
    'TText',
    'TTime',
    'TTimePrecision',
    'TValue',
    'V_IRI',
    'Value',
    'ValueTemplate',
    'ValueVariable',
    'VDatatype',
    'VEntity',
    'VExternalId',
    'VItem',
    'VLexeme',
    'VProperty',
    'VQuantity',
    'VString',
    'VT_IRI',
    'VTEntity',
    'VText',
    'VTime',
    'VTItem',
    'VTProperty',
    'VTValue',
    'VValue',
    'VVDatatype',
)
