# Copyright (C) 2025 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from ..model import Property, Quantity, Text
from ..namespace.semsci import CHEMINF

__all__ = (
    'isotope_atom_count',
    'IUPAC_name',
)

isotope_atom_count = Property(
    CHEMINF.isotope_atom_count_generated_by_pubchem_software_library,
    Quantity).register(
        label='isotope atom count',
        description='isotope atom count generated by pubchem software library')

IUPAC_name = Property(
    CHEMINF.IUPAC_Name_generated_by_LexiChem,
    Text).register(
        label='IUPAC name',
        description='IUPAC Name generated by LexiChem')
