# Copyright (C) 2025 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from ...model import Property, Quantity, Text
from ...namespace.semsci import CHEMINF

__all__ = (
    'isotope_atom_count',
    'IUPAC_name',
    'molecular_weight',
)

isotope_atom_count = Property(
    CHEMINF.isotope_atom_count_generated_by_pubchem_software_library,
    Quantity).register(
        label='isotope atom count',
        description=(
            'isotope atom count generated by pubchem software library'))
"""The isotope atom cound property."""

IUPAC_name = Property(
    CHEMINF.IUPAC_Name_generated_by_LexiChem,
    Text).register(
        label='IUPAC name',
        description='IUPAC Name generated by LexiChem')
"""The IUPAC name property."""

molecular_weight = Property(
    CHEMINF.molecular_weight_calculated_by_the_pubchem_software_library,
    Quantity).register(
        label='molecular weight',
        description=(
            'molecular weight calculated by the pubchem software library'))
"""The molecular weight property."""
